services:
  - type: web
    name: medvoiceai
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: VITE_FORMSPREE_ENDPOINT
        sync: false
